# Start: docker compose -f ./docker-compose.prod.yml --env-file ./.env.prod up
# End: docker compose -f ./docker-compose.prod.yml --env-file ./.env.prod down

version: '3'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    expose:
      - 5432
  web:
    image: ghcr.io/laiskasiili/hisup-explorer/explorer:${IMAGE_VERSION_EXPLORER}
    entrypoint: /usr/local/bin/entrypoint_django_prod.sh
    volumes:
      - static_data:/home/app/staticfiles
      - nginx_conf:/home/app/nginx
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - redis
      - db
    restart: on-failure
  redis:
    image: "redis:alpine"
  celery:
    image: ghcr.io/laiskasiili/hisup-explorer/explorer:${IMAGE_VERSION_EXPLORER}
    entrypoint: /usr/local/bin/entrypoint_celery.sh
    env_file:
      - ./.env.prod
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db
    restart: on-failure
  nginx:
    image: nginx:stable-alpine
    volumes:
      - static_data:/home/app/staticfiles
      - nginx_conf:/etc/nginx/conf.d/
    ports:
      - 8000:80
    depends_on:
      - web
      - redis
      - db
      - celery
volumes:
  postgres_data_prod:
  static_data:
  nginx_conf:
