version: '3'

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    entrypoint: /usr/local/bin/entrypoint_django.sh
    environment:
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
  celery:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    entrypoint: /usr/local/bin/entrypoint_celery.sh
    environment:
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASS=postgres
    ports:
      - 5555:5555
    depends_on:
      - redis, db
