# Start: docker compose -p hisup_explorer -f ./docker-compose.prod.yml up
# End: docker compose -p hisup_explorer -f ./docker-compose.prod.yml down

version: '3'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
    expose:
      - 5432
  web:
    image: ghcr.io/laiskasiili/hisup-explorer/explorer:explorer-v0.0.4
    entrypoint: /usr/local/bin/entrypoint_django_prod.sh
    volumes:
      - static_data:/home/app/staticfiles
    env_file:
      - ./.env.prod
    expose:
      - 8000
    depends_on:
      - redis
      - db
    restart: on-failure
  redis:
    image: "redis:alpine"
  celery:
    image: ghcr.io/laiskasiili/hisup-explorer/explorer:explorer-v0.0.4
    entrypoint: /usr/local/bin/entrypoint_celery.sh
    env_file:
      - ./.env.prod
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db
    restart: on-failure
  nginx:
    image: ghcr.io/laiskasiili/hisup-explorer/nginx:nginx-v0.0.3
    volumes:
      - static_data:/home/app/staticfiles
    ports:
      - 8000:80
    depends_on:
      - web
    restart: on-failure
volumes:
  postgres_data_prod:
  static_data:
