# Generated by Django 3.2.15 on 2022-08-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zoom_level', models.IntegerField(blank=True, default=18)),
                ('bbox_analysis_geojson', models.TextField(blank=True, null=True)),
                ('footprints_geojson', models.TextField(blank=True, null=True)),
                ('is_valid_img', models.BooleanField(blank=True, null=True)),
                ('error_traceback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
